# -*- coding: utf-8 -*-
"""PL HW1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJWaofAYfTAz0C8D7xPF-XFgPWLULIvX

***PL 2 ASSIGNMENT 1(APURVA P KISHORE,2025BSDSAI022)***



**Problem 1:**

 Euclid's Algorithm

**Part 1**




 Implement a function gcd, which takes two integers as its arguments and returns their GCD. You may assume that both inputs are postive integers (i.e. m, n € Z and m, n > 0)
"""

#1.1
def gcd(m, n):
    while n != 0:
        a = m % n
        m = n
        n = a
    return m

#example:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
result = gcd(a, b)
print("The GCD of", a, "and", b, "is", result)

"""**Part 2**


What does your function do if one or both of the arguments are negative?
"""

#1.2
gcd(-12, 8)

#1.2
gcd(-12, -8)

"""ans:If negative numbers are used, the mathematical GCD remains positive, but the program may behave differently unless we convert numbers using absolute value.(modified code is given below)"""

def gcd(m, n):
    m = abs(m)
    n = abs(n)

    while n != 0:
        r = m % n
        m = n
        n = r

    return m
print(gcd(-48,-18))



"""**Problem 2: Approximating Euler's number e**


**Part 1**

 Define a function called euler_limit that takes as an argument an integer n, and returns a float that approximates e by taking x = n in Equation (2). You may assume that the input to your function will be a positive integer (of course, your function will still run just fine if n is, say, a positive float, but we will only use integer values in what follows).


"""

#2.1
def euler_limit(n):
    return (1 + 1/n) ** n
print(euler_limit(67))

"""**Part 2**


What happens when you call euler _limit (n) for really huge values of in (say, 10^16 or 10^18)? Why does this happen?
Hint: the answer has to do with floating point arithmetic. Think about how 1/n is represented on your computer when n is big.

ans:The result becomes exactly 1.0 or inaccurate.


For example:
"""

#2.2
euler_limit(10**16)

"""This happens because of Floating-point arithmetic.

When n is extremely large:
1/n becomes too small for the computer to represent accurately.


So the computer calculates
(1.0)^n = 1
Therefore the approximation becomes incorrect.

**Part 3**


Define a function called euler_sum that takes a single non-negative integer argument n, and returns an approximation to e based on the first n terms of the sum in Equation (1).
"""

#2.3
def factorial(k):
    result = 1
    for i in range(1, k+1):
        result = result * i
    return result
def euler_sum(n):

    if n == 0:
        return 0

    total = 0

    for k in range(n):
        total = total + 1 / factorial(k)

    return total
print(euler_sum(6))

"""Part 4


Define a function called euler_approx that takes a single argument, a positive float epsilon, and uses the sum in Equation (1) to obtain an approximation of e that is within epsilon of the true value of e.

"""

#2.4
import math

def euler_approx(epsilon):

    true_e = math.exp(1)

    total = 0
    k = 0

    while abs(total - true_e) > epsilon:
        total = total + 1 / math.factorial(k)
        k = k + 1

    return total
print(euler_approx(0.0001))

"""Part 5


For a value of interest r and an approximation , we say the difference ^ - x is the error of f(k).
Define functions called print_euler_sum_error and print_euler_lim_error that take a single positive integer n as input.
"""

#2.5
math.exp(1)
import math

def print_euler_sum_error(n):

    true_e = math.exp(1)

    for k in range(1, n+1):
        error = euler_sum(k) - true_e
        print(error)

def print_euler_lim_error(n):

    true_e = math.exp(1)

    for k in range(1, n+1):
        error = euler_limit(k) - true_e
        print(error)
print_euler_sum_error(9)

"""Part 6


Which approximation is better?

ans:The Euler Sum method (faster and stable)is better than the Euler Limit method.
"""



"""**Problem 3: Testing properties of integers**

Part 1


Write a function is_power_of_2 that takes a positive integer as its only argument and returns a Boolean indicating whether or not the input is a power of 2.

"""

#3.1
def is_power_of_2(n):

    if n == 1:
        return True

    if n % 2 != 0:
        return False

    return is_power_of_2(n // 2)
print(is_power_of_2(8))
print(is_power_of_2(11))

"""Part 2


Generalize your previous solution to a function is_power that takes two positive integers as its arguments, b and n, in that order, and returns a Boolean. is_power (b,n) should return True if n is a power of b and False otherwise.
"""

#3.2
def is_power(b, n):

    if n == 1:
        return True

    if n % b != 0:
        return False

    return is_power(b, n // b)
print(is_power(2, 16))
print(is_power(3, 9))
print(is_power(8, 20))



"""**Problem 4: Create and share your repository**

Create a file named "README.md" in the root directory; Include a brief description of the course and the purpose of the repository
Provide the repository link
≤

***ACKNOWLEDGEMENT:I acknowledge that I used AI as a reference tool to understand certain concepts and assist in completing this assignment, while ensuring that the final work reflects my own understanding.***
"""